# Generated by Django 6.0 on 2025-12-28 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TweetPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.CharField(help_text='Unique tweet ID', max_length=50, unique=True)),
                ('username', models.CharField(help_text='User display name', max_length=100)),
                ('screen_name', models.CharField(help_text='User screen name', max_length=100)),
                ('content', models.TextField(help_text='Tweet content')),
                ('created_at', models.DateTimeField(help_text='Tweet creation date')),
                ('retweet_count', models.IntegerField(default=0, help_text='Number of retweets')),
                ('like_count', models.IntegerField(default=0, help_text='Number of likes')),
                ('profile_image_url', models.URLField(blank=True, help_text='User profile image URL')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record update date')),
            ],
            options={
                'verbose_name': 'Tweet',
                'verbose_name_plural': 'Tweets',
                'ordering': ['-created_at'],
            },
        ),
    ]
