# Generated by Django 6.0 on 2025-12-28 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_x', models.IntegerField(help_text='X position in grid')),
                ('position_y', models.IntegerField(help_text='Y position in grid')),
                ('saved_at', models.DateTimeField(auto_now_add=True, help_text='When post was saved')),
                ('original_tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_posts', to='predictor_app.tweetpost')),
            ],
            options={
                'verbose_name': 'Saved Post',
                'verbose_name_plural': 'Saved Posts',
                'ordering': ['position_y', 'position_x'],
                'unique_together': {('position_x', 'position_y')},
            },
        ),
    ]
