# Generated by Django 6.0.1 on 2026-04-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor_app', '0007_tweetpost_real_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetpost',
            name='hashtags',
            field=models.TextField(blank=True, help_text='Comma-separated hashtags from tweet'),
        ),
    ]
